services:
  nginx:
    build:
      context: .
      dockerfile: requirements/nginx/Dockerfile
    # container_name: nginx
    restart: always
    ports:
      - 443:443
    volumes:
      - ./requirements/nginx/conf:/etc/nginx/conf.d

#   db-test:
#     image: mariadb
#     environment:
#       MYSQL_ROOT_PASSWORD: pass
#       MYSQL_DATABASE: my_wordpress_database
#       MYSQL_USER: user
#       MYSQL_PASSWORD: pass
#     volumes:
#       - ./mariadb/data:/var/lib/mysql

#   wp-test:
#     image: wordpress
#     ports:
#       - 8080:80
#     environment:
#       WORDPRESS_DB_HOST: db-test:3306
#       WORDPRESS_DB_USER: user
#       WORDPRESS_DB_PASSWORD: pass
#       WORDPRESS_DB_NAME: my_wordpress_database
#     volumes:
#       - ./wordpress/html:/var/www/html

#   phpmyadmin-test:
#     image: phpmyadmin/phpmyadmin
#     ports:
#       - 8081:80
#     environment:
#       PMA_HOST: db-test
#       PMA_USER: user
#       PMA_PASSWORD: pass

# volumes:
#   db-test:
#   wp-test:
