services:
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    image: nginx
    restart: always
    ports:
      - 443:443
    volumes:
      - ./requirements/nginx/conf:/etc/nginx/conf.d
      - ./requirements/wordpress/html:/var/www/html
    depends_on:
      - wordpress
    networks:
      - inception

  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    image: mariadb
    restart: always
    ports:
      - 3306:3306
    env_file:
      - .env
    networks:
      - inception
  
  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    image: wordpress
    # restart: always
    ports:
      - 9000:9000
    volumes:
      - ./requirements/wordpress/html:/var/www/html
    env_file:
      - .env
    depends_on:
      - mariadb
    networks:
      - inception

networks:
  inception:
    name: inception
# volumes:
#   wordpress:
#   - 